### ISSUE TITLE
ImageIO initialization issue

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/buda-iiif-server#52]
we have the following exception with commit d3bd0ac :

```
nested exception is java.lang.ExceptionInInitializerError] with root cause
java.lang.IllegalArgumentException: provider is null!
	at javax.imageio.spi.ServiceRegistry.setOrdering(ServiceRegistry.java:590)
	at de.digitalcollections.turbojpeg.imageio.TurboJpegImageReaderSpi.lambda$onRegistration$0(TurboJpegImageReaderSpi.java:84)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at de.digitalcollections.turbojpeg.imageio.TurboJpegImageReaderSpi.onRegistration(TurboJpegImageReaderSpi.java:79)
	at javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:731)
	at javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:310)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:211)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at io.bdrc.iiif.image.service.ReadImageProcess.getReader(ReadImageProcess.java:150)
```
while it's ok with commit 6ee3b5a

**Comment by MarcAgate** [comment]
Fixed as of commit 68b2c0c
The reason is unclear and very weird but this fixed it: 
https://github.com/buda-base/buda-iiif-server/commit/68b2c0c43dce90a27f6dfaf76785a119750b3e02#diff-46f1c1ad4c2aa5d8a2b75ec6a1fc869aL21

**Comment by MarcAgate** [comment]
Still, the problem is occurring. Rolling back to  commit 6ee3b5a

**Comment by MarcAgate** [comment]
More: 
Having this issue, I decided to restart the server using: `sudo systemctl restart iiiifserv`

That didn't change anything. However, when I did :
`sudo bash update.sh` (with the same commit) then it fixed the issue. 

It is like something is well set on install (so ImageIO is found) then lost during operations...(ImageIO class cannot be found anymore...)

**Comment by MarcAgate** [comment]
Once again, when I installed the new commit through update.sh, nothing worked correctly and I got the same exception as above...

When I re-ran update.sh, it fixed the issue... I just don't get it !

**Comment by MarcAgate** [comment]
More on that issue:
 if I restart the server and request (jpg): 
https://iiif-dev.bdrc.io/bdr:V4CZ5369_I1KG9127::I1KG91270004.jpg/full/1250,/0/default.jpg

it fails

then I request (tif)
https://iiif-dev.bdrc.io/bdr:V4CZ5369_I1KG9127::I1KG91270004.jpg/full/1250,/0/default.tif

and it works

then I retry (jpg)
https://iiif-dev.bdrc.io/bdr:V4CZ5369_I1KG9127::I1KG91270004.jpg/full/1250,/0/default.jpg 

and it works

So it looks like ImageIO initialization is working when done through a *.tif image request and not with a *.jpg - Once initialized, everything looks fine.

**Comment by MarcAgate** [comment]
The workaround described above is not a valid one. I struggled today with that issue and finally it started to work after I re-ran update.sh
 I received exclusively this exception:

```
[2020-05-19 18:45:40,178 ERROR] cat].[localhost].[/].[dispatcherServlet]: 182 [http-nio-13580-exec-3] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO] with root cause
java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at io.bdrc.iiif.image.service.ReadImageProcess.getReader(ReadImageProcess.java:150)
	at io.bdrc.iiif.image.service.ReadImageProcess.readImageInfo(ReadImageProcess.java:118)
	at io.bdrc.iiif.controllers.IIIFImageApiController.getImageRepresentation(IIIFImageApiController.java:230)
```
I am thinking of installing OracleJDK 8 and give it a try...

**Comment by eroux** [comment]
the best would be to install openjdk on your machine I think

**Comment by MarcAgate** [comment]
Done, now it fails on my machine as well

**Comment by MarcAgate** [comment]
Instead of moving to oracle Jdk 8, we actually moved to openJdk11 on both environements (buda1 and buda3) as openJdk 11 will be the official version of java for debian 10.
This solved the problem.
