### ISSUE TITLE
NPE on setcookie

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#70]
here's the log:

```
[2021-02-01 10:19:00,049 ERROR] cat].[localhost].[/].[dispatcherServlet]: 182 [http-nio-13580-exec-12] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.NullPointerException: null
	at io.bdrc.auth.UserProfile.<init>(UserProfile.java:50)
	at io.bdrc.auth.TokenValidation.<init>(TokenValidation.java:50)
	at io.bdrc.iiif.auth.IIIFRdfAuthFilter.doFilter(IIIFRdfAuthFilter.java:68)
```

**Comment by eroux** [comment]
fixed in https://github.com/buda-base/bdrc-auth-lib/commit/5ab2a51d21d8a6e176e2477480aff7e2f7fb11de
